#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2012 OpenWrt.org

START=80
USE_PROCD=1

STATUS=Y

uci_get_by_type(){
	local ret=$(uci get https-dns-proxy.@base[0].$1 2>/dev/null)
	echo ${ret:=$2}
}

start_upstream(){
	cat > /tmp/dnsmasq.d/https-dns-proxy.conf <<EOF
no-resolv
server=$ip#$port
EOF
}

service_triggers() {
	procd_add_reload_trigger 'https-dns-proxy'
}

start_service(){
	[ $(uci_get_by_type enabled 0) = 0 ] && A=1 && return 1
	url=$(uci_get_by_type url 0)
	[ "$url" = "0" ] && url='https://dns.alidns.com/dns-query'
	dns=$(uci_get_by_type dns isp)
	if [ "$dns" = "isp" ];then
		dns=$(echo $(cat /tmp/resolv.conf.auto 2>/dev/null | grep nameserver | awk '{print $2}') | sed "s/\s\+/,/g")
		while [ -z $dns ];do
			sleep 1
			dns=$(echo $(cat /tmp/resolv.conf.auto | grep nameserver | awk '{print $2}') | sed "s/\s\+/,/g")
		done
	fi
	dns=$(echo $dns | sed "s/，/,/g" | sed "s/。/./g" | sed "s/：/:/g" | sed "s/【/[/g" | sed "s/】/]/g" | sed "s/[^0-9A-Fa-f]*$//g")
	param="-b $dns -r $url"
	ip=$(uci_get_by_type ip 127.0.0.1)
	[ "$ip" != "127.0.0.1" ] && param="$param -a $ip"
	port=$(uci_get_by_type port 5053)
	[ "$port" != "5053" ] && param="$param -p $port"
	[ $(uci_get_by_type ipv4 0) = 1 ] && param="$param -4"
	procd_open_instance
	procd_set_param command /usr/sbin/https-dns-proxy $param
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param respawn
	procd_close_instance
	if [ $(uci_get_by_type mode 1) = 1 ] && [ $STATUS = Y ];then
		start_upstream
		[ -f /var/lock/https-dns-proxy.lock ] || /etc/init.d/dnsmasq restart >/dev/null 2>&1
	fi
}

stop_service(){
	if [ $STATUS = Y ] && [ -f /tmp/dnsmasq.d/https-dns-proxy.conf ];then
		rm -f /tmp/dnsmasq.d/https-dns-proxy.conf
		/etc/init.d/dnsmasq restart >/dev/null 2>&1
	fi
}

reload_service(){
	restart
}

restart(){
	STATUS=N
	A=0
	stop
	start
	if [ $A = 0 ] && [ $(uci_get_by_type mode 1) = 1 ];then
		if [ "$(cat /tmp/dnsmasq.d/https-dns-proxy.conf 2>/dev/null | grep server= | sed 's/[^#]*#//g')" != "$port" ];then
			start_upstream
			A=2
		elif [ "$(cat /tmp/dnsmasq.d/https-dns-proxy.conf 2>/dev/null | grep server= | sed 's/server=//g' | sed 's/#*[^#]*$//g')" != "$ip" ];then
			start_upstream
			A=2
		fi
	else
		if [ -f /tmp/dnsmasq.d/https-dns-proxy.conf ];then
			rm -f /tmp/dnsmasq.d/https-dns-proxy.conf
			A=2
		fi
	fi
	[ $A = 2 ] && /etc/init.d/dnsmasq restart >/dev/null 2>&1
}

boot(){
	if [ "$(uci -q get adbyby.@adbyby[0].enable)" = "1" ];then
		touch /var/lock/https-dns-proxy.lock
	elif [ -n "$(uci -q get shadowsocksr.@global[0].global_server)" ] && [ "$(uci -q get shadowsocksr.@global[0].global_server)" != "nil" ];then
		touch /var/lock/https-dns-proxy.lock
	fi
	start
	rm -f /var/lock/https-dns-proxy.lock
}
